torchrun \
--nproc_per_node 1 \
--nnodes 1 \
--node_rank 0 \
llama3_finetune.py \
--model_name_or_path "/run/determined/workdir/llama3-8b" \
--data_path "/run/determined/workdir/data/entity_train.json" \
--fp16 True \
--output_dir "/run/determined/workdir/output/llama3_8B_lora" \
--num_train_epochs 5 \
--per_device_train_batch_size 1 \
--per_device_eval_batch_size 1 \
--gradient_accumulation_steps 4 \
--evaluation_strategy "no" \
--save_strategy "steps" \
--save_steps 5 \
--save_total_limit 1 \
--learning_rate 1e-5 \
--weight_decay 0.1 \
--adam_beta2 0.95 \
--warmup_ratio 0.01 \
--lr_scheduler_type "cosine" \
--logging_steps 1 \
--report_to "none" \
--model_max_length 1024 \
--gradient_checkpointing True \
--lazy_preprocess True \
--deepspeed "/run/determined/workdir/configs/ds_config_zero2.json" \
--use_lora